### ISSUE TITLE
CON - AJUS - Actualizar los datos diariamente de adicionales prestamos 

### ISSUE THREAD

**Issue by AGimenezIA** [InteligenciaAnalitica/PETERSEN#1868]
Referente: Nicolas Zuliani

**Comment by CamiloPereyra01** [comment]
Se pasó a Bloqueado debido a que se Informó lo que se debia hacer a Martin Pastrana. Se escogio una solucion y se explico por qué. Queda que realicemos una reunion entre todos, nico martin abi cami ale fabri.
![image.png](https://images.zenhubusercontent.com/61797b4c2b89e726d466da98/38e652ea-a69d-4c45-a7c1-a1dd1da060b4)

**Comment by CamiloPereyra01** [comment]
![image.png](https://images.zenhubusercontent.com/61797b4c2b89e726d466da98/1e69001f-8711-4c10-a68a-645bbf3eb8ac)

**Comment by CamiloPereyra01** [comment]
Se realizo la reunion con usarios, se debe realizar el levantamiento de informacion de la tabla de prestamos  directamente desde SFB, por lo tanto modificar el universo para que lo tome correctamente, filtrar por fecha y contemplar lo mismo para todas las tablas que consultaban a Unisys

**Comment by CamiloPereyra01** [comment]
Estado de este RQ: Se solicitó a DBA que nos envien la informacion de la conexion Sfb correspondiente ya que no corresponde a la histo_sfb la cual siempre tratamos en BI. Mail ![image.png](https://images.zenhubusercontent.com/61797b4c2b89e726d466da98/7cf0db05-738f-4aa7-87fd-65ec47425a91)

**Comment by CamiloPereyra01** [comment]
Se modifico el proceso de carga vuelco online![image.png](https://images.zenhubusercontent.com/61797b4c2b89e726d466da98/e86b0439-38ee-452c-8e26-90f31aa3ca32)

**Comment by CamiloPereyra01** [comment]
Para que suceda esto anteriormente se realizo, la funcion Generate_key_bi. Campo de Fecha requerido por Usuario. Extraccion de cada una de las cuatro tablas, cargandolas como origen de datos las mismas tablas con el mismo nombre pero linkeada a @SFB.  Se crearon vistas de cada una de estas para implementar los dos campos mencionados anteriomente. Y se consulto a usuario si existe algun filtro de fecha para las tablas, con el obkjetivo de que el paquete no tarde mucho. debido a que exxiste una tabla que de @sfb trae 9 millones de registros. esto tarda... aprox 25min en un paquete. Por suerte ya existia una tabla con esa cantidad de registros en el pauqete. pero.. se agregarian dos mas.. asi que espero el tema del campo para filtrar fecha

**Comment by CamiloPereyra01** [comment]
En espera de validacion de usuarios: ![image.png](https://images.zenhubusercontent.com/61797b4c2b89e726d466da98/f8bba3f6-b14c-4224-95a0-c9a091a8aaa5)

**Comment by CamiloPereyra01** [comment]
Una vez que nico Valide y si es que esta todo Ok, se debe pasar al Job el Paquete de Vuelcos Online

**Comment by CamiloPereyra01** [comment]
Usuario nicolas dijo que no veia unos prestamos pero era pq no se habia pasado al job, ahora que se paso y se actualizan las tablas diariamente, la informacion que decia que no estaba, ahora se encuentra.

**Comment by CamiloPereyra01** [comment]
![image.png](https://images.zenhubusercontent.com/61797b4c2b89e726d466da98/cbab9dcb-faec-4045-8a1d-1c31f8cad7d4)

**Comment by CamiloPereyra01** [comment]
[Uploading... image.png]

**Comment by CamiloPereyra01** [comment]
en espera validacion de usuarios*. Nico Paternidad por ende no va a responder
