### ISSUE TITLE
PLA - AJUS - Ajustar Reporte ENT – Top Transferencias por monto del sector publico Exportar

### ISSUE THREAD

**Issue by AGimenezIA** [InteligenciaAnalitica/PETERSEN#1982]
Referente: Carlos Mellado

Reporte ENT – Top Transferencias por monto del sector publico Exportar

Respecto de este reporte está tomando las transferencias del Ministerio de Economía que van a cuentas de otros entes públicos, por alguna razón no las esta excluyendo. Respecto de esto es mas que nada para verificar que es lo que puede estar ocurriendo y si ven de alguna manera el beneficiario de las transferencias emitidas.

**Comment by CamiloPereyra01** [comment]
Se movio a dar seguimiento debido a que el ultimo inconveniente era que no venian 2 txs. La cual ya habiamos corregido con el ultimo pase a produccion. Mail  en el cual le consultamos si quiere reprocesar mayo e informamos la siguacion a  Carlos: ![image.png](https://images.zenhubusercontent.com/61797b4c2b89e726d466da98/6a3afadc-0c50-467b-9d4b-5bff4795321c)

**Comment by CamiloPereyra01** [comment]
Se movio a en curso porque no hubo registros para el mes de junio, vinieron erroneos.

**Comment by CamiloPereyra01** [comment]
DBA Reprocesaron lo solictado y Usuarios validaron y salio todo correcto. . Mail ![image.png](https://images.zenhubusercontent.com/61797b4c2b89e726d466da98/2163f3cd-1b06-42b8-9dd0-fed6d57098f5)

**Comment by CamiloPereyra01** [comment]
Se paso a pendiente debido al analisis de porque para el clietne  Caja previsional no viene beneficiario

**Comment by CamiloPereyra01** [comment]
en curso de buscar  las txs de Caja Previsional.

**Comment by CamiloPereyra01** [comment]
No se hablo nada en la reunion, se consultara en minuta 19/9

**Comment by CamiloPereyra01** [comment]
Pase a produccion implementado y despues todo validado
